base/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('snippet/<str:pk>', views.snippet, name='snippet'),

    path('login/', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
    path('logout/', views.logoutPage, name='logout'),

    path('create-snippet/', views.createSnippet, name='create-snippet'),
    path('auto-code/', views.autoCode, name='auto-code'),
    path('code-explain/', views.codeExplain, name='code-explain'),
    path('code-translate/', views.codeTranslate, name='code-translate')

]

codeblocks/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
]

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=True)
    
    # Use email instead of username
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class Language(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name


class Snippet(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200)
    code = models.TextField(blank=False)
    # Takes a snapshot everytime we save
    updated = models.DateTimeField(auto_now=True)
    # Takes a snapshot only when created
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    snippet = models.ForeignKey(Snippet, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    # Takes a snapshot only when created
    created = models.DateTimeField(auto_now_add=True)

     # To view the newest Message first
    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body



class Explain(models.Model):
    explain = models.TextField(max_length=4000)

    def __str__(self):
        return self.explain


class Translate(models.Model):
    first_language = models.CharField(max_length=200, null=True)
    second_language = models.CharField(max_length=200, null=True)
    translate = models.TextField(max_length=4000)


    def __str__(self):
        return self.translate

base/forms.py
from django.forms import ModelForm, TextInput
from .models import Snippet, Translate, User, Explain
from django.contrib.auth.forms import UserCreationForm

# Creating form based on the db models
class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']


class SnippetForm(ModelForm):
    class Meta:
        model = Snippet
        fields = '__all__'
        exclude = ['author']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'id': 'editor'
        })


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email']


class ExplainForm(ModelForm):
    class Meta:
        model = Explain
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'id': 'editor',
                'type': 'submit',
                'name': 'explain',
                'value': '{{form.explain}}'
        })


class TranslateForm(ModelForm):
    class Meta:
        model = Translate
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'id': 'editor'
        })

base/views.py
from django.shortcuts import redirect, render
from django.db.models import Q
from .models import User, Language, Snippet, Comment, Explain, Translate
from .forms import ExplainForm, MyUserCreationForm, TranslateForm, UserForm, SnippetForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_protect

# from codecarbon import EmissionsTracker
import openai
import os
from dotenv import load_dotenv
from djangocodemirror.settings import *
load_dotenv()


openai.api_key = os.getenv('OPENAI_API_KEY')

# Create your views here.
def index(request):
    return render(request, 'base/index.html')



def loginPage(request):
    page = 'login'

    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')
 
        try:
            user = User.objects.get(email=email)
        except:
            messages.error(request, 'User does NOT exists!')
        
        # Authentication
        user = authenticate(request, email=email, password=password)
        if user is not None:
            # Adds session in db and browser
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Credentials Incorrect')

    context = {'page':page}
    return render(request, 'base/login_register.html', context)



def registerPage(request):
    form = MyUserCreationForm

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'An error occured during registration!')
    
    context = {'form':form}
    return render(request, 'base/login_register.html', context)



def logoutPage(request):
    logout(request)
    return redirect('home')



def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    snippets = Snippet.objects.filter(Q(language__name__icontains=q) |
                                  Q(name__icontains=q) |
                                  Q(code__icontains=q)
    )

    languages = Language.objects.all()

    # ChatBot
    if request.GET.get('res') != None:

        res = request.GET.get('res')
        reply = openai.Completion.create(
        model="text-davinci-003",
        prompt=f"You are a chatbot who only answers questions about coding, computer science, AI, software development, Information Technology and closely related fields and don't entertain other questions. Answer the following question:\n\n{res}?",
        temperature=0.3,
        max_tokens=60,
        top_p=1,
        frequency_penalty=0.5,
        presence_penalty=0,
        stop=["You:"]
        )
        final_answer = reply["choices"][0]["text"].lstrip()
        context = {'snippets':snippets, 'languages':languages,
        'reply':reply, 'final_answer':final_answer, 'res':res}
        return render(request, 'base/home.html', context)

    else:
        context = {'snippets':snippets, 'languages':languages}
        return render(request, 'base/home.html', context)


def snippet(request, pk):
    snippet = Snippet.objects.get(id=pk)
    snippet_comments = snippet.comment_set.all()

    # To add a new message
    if request.method == 'POST':
        if request.user.is_authenticated:
            comment = Comment.objects.create(
                user = request.user,
                snippet = snippet,
                body = request.POST.get('body')
            )
            
            return redirect('snippet', pk=snippet.id)
        else:
            return redirect('login')

    context = {'snippet':snippet, 'snippet_comments':snippet_comments}
    return render(request, 'base/snippet.html', context)



@login_required(login_url='login')
def createSnippet(request):
    form = SnippetForm()
    languages = Language.objects.all()

    if request.method == 'POST':
        language_name = request.POST.get('language')

        language, created = Language.objects.get_or_create(name=language_name)

        # Snippet creation
        Snippet.objects.create(
            author = request.user,
            language = language,
            name = request.POST.get('name'),
            code = request.POST.get('code')
        )
        return redirect('home')
    
    
    context = {'form':form, 'languages':languages}
    return render(request, 'base/create_snippet.html', context)



@login_required(login_url='login')
def deleteSnippet(request, pk):
    snippet = Snippet.objects.get(id=pk)

    if request.user != snippet.author:
        messages.error(request, 'you are not allowed here')
    
    if request.method == 'POST':
        snippet.delete()
        return redirect('home')

    return render(request, 'base/delete.html', {'obj':snippet})




def autoCode(request):
    if request.GET.get('p'):
        p = request.GET.get('p')
        response = openai.Completion.create(
            model="text-davinci-003",
            prompt=f"The user is novice to programming. Write a code for the following prompt:\n\n{p}",
            temperature=0,
            max_tokens=1000 ,
            top_p=1,
            frequency_penalty=0.2,
            presence_penalty=0
        )
        final_answer = response["choices"][0]["text"].lstrip()
        context = {'response':response, 'final_answer':final_answer, 'p':p}
        return render(request, 'base/autocode.html', context)

    context = {}
    return render(request, 'base/autocode.html', context)



def codeExplain(request):
    form = ExplainForm
    explain = Explain.objects.all()
    

    if request.method == 'POST':
        get_explain_code = request.POST.get('explain')

        Explain.objects.create(
            explain = request.POST.get('explain')
        )

        answer = openai.Completion.create(
        model="text-davinci-003",
        prompt="The user is a novice in programming. Explain the following code in detail. Use bullet points if required\n\n"+str(Explain.objects.last()),
        temperature=0,
        max_tokens=1000,
        top_p=1,
        frequency_penalty=0,
        presence_penalty=0
        )

        final_answer = answer["choices"][0]["text"].lstrip()
        print(final_answer)

        # To reload the page with prefilled form
        form = ExplainForm(initial={'explain':f'{str(Explain.objects.last())}'})
        context = {'form':form, 'explain':explain, 'final_answer':final_answer}
        return render(request, 'base/explain.html', context)
    context = {'form':form}
    return render(request, 'base/explain.html', context)



def codeTranslate(request):
    form = TranslateForm
    get_translate = Translate.objects.all()
    

    if request.method == 'POST':
        first_language = request.POST.get('first_language')
        second_language = request.POST.get('second_language')
        translate = request.POST.get('translate')

        Translate.objects.create(
            translate = request.POST.get('translate'),
            first_language = request.POST.get('first_language'),
            second_language = request.POST.get('second_language')
        )
        
        answer = openai.Completion.create(
        model="text-davinci-003",
        prompt=f"##### The user is a novice to programming. Translate the following code from {first_language} into {second_language}. Translate the code such the translated code is ready to be executed.\n### {first_language}\n\n{translate}\n\n### {second_language}\n\n",
        temperature=0.05,
        max_tokens=800,
        top_p=1,
        frequency_penalty=0,
        presence_penalty=0
        )
        final_answer = answer["choices"][0]["text"].lstrip()

        # To access the latest field values from the database
        latest_object = Translate.objects.latest('id')
        translate_from = latest_object.first_language
        translate_to = latest_object.second_language
        code = latest_object.translate

        # print(a)
        # print(b)
        # print(c)
        form = TranslateForm(initial={'first_language':f'{translate_from}','second_language':f'{translate_to}', 'translate':f'{code}' })

        context = {'form':form, 'final_answer':final_answer}

        return render(request, 'base/translate.html', context)

    context = {'form':form}
    return render(request, 'base/translate.html', context)

base/templates/base/autocode.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<head>
    <!-- other content of the head element goes here -->
    <link rel="stylesheet"
        href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.3.1/build/styles/base16/atelier-estuary.min.css">
    <script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.3.1/build/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
</head>
<style>
    pre,
    code {
        font-family: monospace, monospace;
    }

    pre {
        overflow: auto;
    }

    pre>code {
        display: block;
        padding: 1rem;
        word-wrap: normal;
    }
</style>


<main class="profile-page layout layout--2">
    <div class="container">
        <!-- Room Start -->
        <div class="room">
            <div class="room__top">
                <div class="room__topLeft">
                    <a href="{% url 'index' %}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>AUTO CODE</h3>
                </div>

                <div class="room__topRight">


                </div>

            </div>
            <div class="room__box scroll">
                <div class="">
                    <br><br>
                    <form class="header__search" method="GET" action="{% url 'auto-code' %}">
                        <label>
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>autocode</title>
                                <path
                                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
                                </path>
                            </svg>
                            <input name="p" placeholder="Write your prompt to generate code!" />
                        </label>
                    </form>
                    <div class="room__info">
                        <h3></h3>
                        <span></span>
                    </div>
                    <div class="room__hosted">
                        <p></p>
                        <a href="" class="room__author">
                        </a>
                    </div>
                    <div class="room__details" style="overflow-y: scroll; height: 420px;">
                        {% if p == '' %}
                         ...
                         {% else %}
                        <pre><code>{{final_answer}}</code></pre>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <!-- Room End -->

        <!--   Start -->
        <div class="participants">
            <!-- <h3 class="participants__top">Comments</h3>
            <div class="participants__list scroll">
            {% for comment in snippet_comments %}
            <div class="thread">
                <div class="thread__top">
                    <div class="thread__author">
                        <a href="" class="thread__authorInfo">
                            <div class="avatar avatar--small">
                                <img src="{% static 'images/avatar.svg' %}" />
                            </div>
                            <span>@{{comment.user.username}}</span>
                        </a> -->
            <!-- <span class="thread__date">{{comment.created|timesince}} ago</span> -->
            <!-- </div>
                </div>
                <div class="thread__details">
                   <b>{{comment.body}}</b> 
                </div>
            </div>
            {% endfor %}

                <div class="room__message">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <input name="body" placeholder="Write your comment here..." />
                    </form>
                </div>
            </div> -->
        </div>
    </div>
</main>
{% endblock content%}

base/templates/base/chat.html
<div class="activities">

    <div class="activities__header">
        <h2>Ask Me Anything!</h2>
    </div>
    <div class="activities__box">
    {{final_answer}}
    </div>
    <div class="activities__box">

        <form class="header__search" method="GET" action="{% url 'home' %}">
            <input name="res" placeholder="Ask Your Question here!." />
        </form>

    </div>
</div>

base/templates/base/create_snippet.html
{% extends 'main.html' %}

{% block content%}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/codemirror.min.css"
    integrity="sha512-uf06llspW44/LZpHzHT6qBOIVODjWtv4MxCricRxkzvopAlSWnTf6hpZTFxuuZcuNE9CBQhqE0Seu1CoRk84nQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/codemirror.min.js"
    integrity="sha512-8RnEqURPUc5aqFEN04aQEiPlSAdE0jlFS/9iGgUyNtwFnSKCXhmB6ZTNl7LnDtDWKabJIASzXrzD0K+LYexU9g=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/theme/dracula.min.css"
    integrity="sha512-gFMl3u9d0xt3WR8ZeW05MWm3yZ+ZfgsBVXLSOiFz2xeVrZ8Neg0+V1kkRIo9LikyA/T9HuS91kDfc2XWse0K0A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/mode/xml/xml.min.js"
    integrity="sha512-LarNmzVokUmcA7aUDtqZ6oTS+YXmUKzpGdm8DxC46A6AHu+PQiYCUlwEGWidjVYMo/QXZMFMIadZtrkfApYp/g=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/mode/python/python.min.js"
    integrity="sha512-2M0GdbU5OxkGYMhakED69bw0c1pW3Nb0PeF3+9d+SnwN1ryPx3wiDdNqK3gSM7KAU/pEV+2tFJFbMKjKAahOkQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/theme/base16-dark.min.css"
    integrity="sha512-CNZkbIVu/G4dB3YpFIZgMtE45vHp/QocgMbf6jg+DFFPLN3emncIob8ubKANmsGQ8JsnzzSVTj7WrFrnx6EgXQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />







<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Create Snippet</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" id="form" action="" method="POST">
          {% csrf_token %}



          <div class="form__group">
            <label for="room_name">Enter a Language</label>
            <input required type="text" value="{{snippet.language.name}}" name="language" list="topic-list" />
            <datalist id="topic-list">
              <select id="room_topic">
              {% for language in languages %}
              <option value="{{language.name}}">{{language.name}}</option>
              {% endfor %}
              </select>
            </datalist>
          </div>


          <div class="form__group">
            <label for="room_description">Code</label>
            {{form.code}}
          </div>

          <div class="form__group">
            <label for="room_topic">Snippet Name</label>
            {{form.name}}
          </div>

          

          <div class="form__action">
            <a class="btn btn--dark" href="{% url 'home' %}">Cancel</a>
            <button class="btn btn--main" onclick="myFunction()" type="button">Submit</button>
          </div>
      </form>
      <script>
        function myFunction() {
            document.getElementById("form").submit();
        } 
        var editor = CodeMirror.fromTextArea(document.getElementById('editor'), {
                mode: 'python',
                theme: 'base16-dark', 
                lineNumber: true,
            });
      </script>
      </div>
    </div>
  </div>
</main>

{% endblock content %}

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}
    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <!-- Used to send back the user from the page where they came from-->
                        <a href="{{request.META.HTTP_REFERER}}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" method="POST" action="">
                        {% csrf_token %}
                        <div class="form__group">
                            <p>Are you sure you want to delete "{{obj}}"?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm" />
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>


    {% endblock content %}

base/templates/base/explain.html
{% extends 'main.html' %}
{% load static %}
{% block content %}


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/codemirror.min.css"
    integrity="sha512-uf06llspW44/LZpHzHT6qBOIVODjWtv4MxCricRxkzvopAlSWnTf6hpZTFxuuZcuNE9CBQhqE0Seu1CoRk84nQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/codemirror.min.js"
    integrity="sha512-8RnEqURPUc5aqFEN04aQEiPlSAdE0jlFS/9iGgUyNtwFnSKCXhmB6ZTNl7LnDtDWKabJIASzXrzD0K+LYexU9g=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/theme/dracula.min.css"
    integrity="sha512-gFMl3u9d0xt3WR8ZeW05MWm3yZ+ZfgsBVXLSOiFz2xeVrZ8Neg0+V1kkRIo9LikyA/T9HuS91kDfc2XWse0K0A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/mode/xml/xml.min.js"
    integrity="sha512-LarNmzVokUmcA7aUDtqZ6oTS+YXmUKzpGdm8DxC46A6AHu+PQiYCUlwEGWidjVYMo/QXZMFMIadZtrkfApYp/g=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/mode/python/python.min.js"
    integrity="sha512-2M0GdbU5OxkGYMhakED69bw0c1pW3Nb0PeF3+9d+SnwN1ryPx3wiDdNqK3gSM7KAU/pEV+2tFJFbMKjKAahOkQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/theme/base16-dark.min.css"
    integrity="sha512-CNZkbIVu/G4dB3YpFIZgMtE45vHp/QocgMbf6jg+DFFPLN3emncIob8ubKANmsGQ8JsnzzSVTj7WrFrnx6EgXQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<style>
    .home-container {
        display: grid;
        grid-template-columns: 1fr 1fr;
    }
</style>
<main class="profile-page layout layout--2">
    <div class="home-container">
        <!-- Room Start -->
        <div class="room" style="margin-left: 2rem; margin-right: 2rem;">
            <div class="room__top">
                <div class="room__topLeft">
                    <a href="{% url 'index' %}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Code to explain</h3>
                </div>
            </div>
            <div class="room__box scroll">
                <!-- <div class=""> -->
                    <br><br>



                    <!-- USER INPUT -->
                    <form class="form" id="form" action="" method="POST">
                        {% csrf_token %}
                        <div class="form__group">
                            <p class="roomListRoom__topic" style="margin-bottom: 0.5rem;">Your code goes here!</p>
                            {{form.explain}}
                        </div>


                        <div class="form__action">
                            <button class="btn btn--main" type="button" onclick="myFunction()">Submit</button>
                        </div>
                        
                      </form>
                      <script>
                        function myFunction() {
                            document.getElementById("form").submit();
                        } var editor = CodeMirror.fromTextArea(document.getElementById('editor'), {
                                mode: 'python',
                                theme: 'dracula', 
                                lineNumber: true,
                            }); </script>


                                <div class="room__info">
                                    <h3></h3>
                                    <span></span>
                                </div>
                                <div class="room__hosted">
                                    <p></p>
                                    <a href="" class="room__author">
                                    </a>
                                </div>
                                <div class="room__details" style="overflow-y: scroll; height: 420px;">

                                    <pre><code></code></pre>

                                </div>
                        <!-- </div> -->
                </div>
            </div>
            <!-- Room End -->

            <!--   Start -->
            <div class="room" style="margin-left: 2rem; margin-right: 2rem;">
                <div class="room__top">
                    <h3>RESULT</h3>
                </div>
                <div class="room__box scroll">
                    <div class="">
                        <br><br>

                        <div class="room__info">
                            <h5>{{final_answer|linebreaks}}</h5>
                            <span></span>
                        </div>

                       
                    </div>
                </div>
            </div>

        </div>
</main>

{% endblock content %}

base/templates/base/language_component.html
{% load static %}
<div class="topics">
    <div class="topics__header">
      <h2>Browse Languages</h2>
    </div>
    <ul class="topics__list">
      <li>
        <a href="{% url 'home' %}" class="active">Total Languages <span>{{languages.count}}</span></a>
      </li>
      {% for language in languages %}
      <li>
        <a href="{% url 'home' %}?q={{language.name|urlencode}}"><img src ="{% static 'images/' %}{{language.name|urlencode|lower}}.svg" style="width: 32px; height:32 px;">{{language}} <span>{{language.snippet_set.count}}</span></a>
      </li>
      {% endfor %}
    </ul>
    <!-- <a class="btn btn--link" href="languages.html">
      More
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>chevron-down</title>
        <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
      </svg>
    </a> -->
  </div>